version: "3.7"

services:

  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: cursolaravel
    container_name: cursolaravel-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cursolaravel

  db:
    image: mysql:5.7
    container_name: cursolaravel-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - cursolaravel

  nginx:
    image: nginx:1.17-alpine
    container_name: cursolaravel-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - cursolaravel

networks:
  cursolaravel:
    driver: bridge
